baseurl = "https://gainesfilm.ccnmtl.columbia.edu/"
languageCode = "en-us"
title = "The Film and Media Studies Digital Library"
paginate = 20

[taxonomies]
course = "courses"
category = "categories"
media = "media"
year = "years"
